### ISSUE TITLE
[BUG]: Caster Gilgamesh NP refund too high?

### ISSUE THREAD

**Issue by DigitalTrain** [gakiloroth/gakiloroth.github.io#22]
Just a quick example of my crappy Caster Gilgamesh:

Level 70, 9029 attack, NP 1 non-strengthened (450% multiplier).

10% NP Strength, 140% Arts, 10.5% ATK, 60% NP Gain.

Fighting three Berserker enemies: 40868, 46414, 40868 all earth attribute.

Expected minimum NP Refund in calculator: 88.20%.

Actual Refund: 46%

EDIT:
It looks like his "npchargeatk" value is double what it should be? Says 0.32 when it's actually 0.16, I think.

**Comment by gakiloroth** [comment]
Thanks - turns out CasGil (along with EMIYA Assassin and Hundred Faces Hassan) have different NP gain mod for their NP Card vs their other cards. The way I was building my sheet seemed to pull from just Buster card so Cas Gil had 2x the amount of np gain he should have. https://apps.atlasacademy.io/db/JP/servant/145

Should be fixed by https://github.com/gakiloroth/gakiloroth.github.io/commit/7e131297ee1ebf2ad0a264a8701acc67c5cb5893

**Comment by gakiloroth** [comment]
Just saw you also left a comment about what the issue might've been - saw it after I had already dug in myself, but I appreciate it!
